replicaCount: 1

image:
  repository: amanpandey3956/go-devops-project
  pullPolicy: IfNotPresent
  tag: "22928556236"

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
